# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160327_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the category.', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='A description of the Product for the website.')),
                ('is_organic', models.BooleanField(default=False, help_text='Is this Product Certified Organic?')),
                ('is_heirloom', models.BooleanField(default=False, help_text='Is this Product an Heirloom?')),
                ('is_south_east', models.BooleanField(default=False, help_text='Is this Product suited for the South East?')),
                ('is_active', models.BooleanField(default=False, help_text='Is this Product Active?')),
                ('category', models.ForeignKey(help_text='The Category the Product belongs to.', on_delete=django.db.models.deletion.PROTECT, to='products.Category')),
            ],
        ),
    ]
