# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='The SKU of this Variant.', max_length=10, unique=True)),
                ('weight', models.PositiveIntegerField(help_text='The weight of this Variant in milligrams.')),
                ('price', models.PositiveIntegerField(help_text='The price of this Variant in cents.')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='The name of the Product.', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(help_text='The Product of this Variant.', on_delete=django.db.models.deletion.PROTECT, to='products.Product'),
        ),
    ]
