# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20160327_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='The name of the category.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='The name of the Product.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(help_text='The SKU of this Variant.', max_length=20, unique=True),
        ),
    ]
