# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20160327_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='The available quanitity of this Variant.'),
            preserve_default=False,
        ),
    ]
